build: run buf action only on triggers from within the repo
redpanda-data/console pull request #1434
Opened 2024-09-05 16:50 UTC by bojand

Substitute for https://github.com/redpanda-data/console/pull/1425.

Currently the this action fails on PRs from forks due to `aws-actions/configure-aws-credentials` workflow which does not have access to secrets and vars in that context. 

This PR makes the GH Action conditional to only run on PRs from within branches, along with push to master.
This should cover most cases since normally the Console team should be updating the protos.
Exceptions are docs updates by docs team, or external contributions. But we can work around those cases or offer manual fixes.

2024-09-05 16:56 UTC, weeco approved these changes

2024-09-05 19:43 UTC, andrewhsu requested changes
suggested `if:` guard to have the step skipped if PR from forked repo, but allow the step to run after merge to `master`

2024-09-05 19:43 UTC, andrewhsu commented on .github/workflows/buf.yml
> +    if: github.repository == 'redpanda-data/console'
```suggestion
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == 'redpanda-data/console' }}
```
i suggest similar changes to https://github.com/redpanda-data/connect/pull/2825#discussion_r1745848682

2024-09-06 23:15 UTC, andrewhsu approved these changes
i made suggestion, but in general LGTM

2024-09-06 23:15 UTC, andrewhsu commented on .github/workflows/buf.yml
>        - proto/**.proto
```suggestion
      - .github/workflows/buf.yml
      - proto/**.proto
```
i suggest also having this workflow run on PRs that change the workflow yaml file so you can also ensure the `if:` stmt is doing what you want

2024-09-09 14:13 UTC, merged