Sj/fix topic config
redpanda-data/console pull request #748
Opened 2023-06-28 17:58 UTC by sago2k8

Fix issue when opening the modal for change topic configuration.

We needed to provide the Theme to the Portal Antd uses for showing the modals, easiest was to reuse the ChakraProvider.

2023-06-28 20:35 UTC, malinskibeniamin approved these changes
Nice work! Thanks for pairing, it was good to know how console setup works

2023-06-28 20:35 UTC, malinskibeniamin commented on frontend/package.json
> +        "@chakra-ui/react-use-disclosure": "^2.0.8",
Is it possible to add them as peer dependencies? Ideally we should import everything from Redpanda UI as it re-exports the entire chakra UI

2023-06-28 20:35 UTC, malinskibeniamin commented on frontend/src/components/pages/topics/TopicConfiguration.tsx
> +                    <ChakraProvider theme={redpandaTheme} disableGlobalStyle={true} disableEnvironment={true}>
Nice one! I think as long as we add a follow up GH issue to remove the theme after using the chakra modal, this will work fine in the meantime

2023-06-29 12:59 UTC, rikimaru0345 requested changes

2023-06-29 12:59 UTC, rikimaru0345 commented on frontend/src/components/pages/topics/TopicConfiguration.tsx
> +                                    <div onClick={e => {
```suggestion
                                    <div style={{ position: 'relative', zIndex: 2 }}  onClick={e => {
```

2023-06-30 10:01 UTC, rikimaru0345 approved these changes

2023-06-30 10:05 UTC, merged